# netCDF files of beetle presence data

library(ncdf4)

<<<<<<< HEAD
# path
csvpath <- "/projects/bonelab/dongmeic/beetle/csvfiles/"
=======
# path in ACISS
csvpath <- "/gpfs/projects/gavingrp/dongmeic/beetle/csvfiles/"
>>>>>>> 9f55ce8226a09b90391de27a36b1dd0e12786bc9

# open points netCDF file to get dimensions, etc.
ncpath <- "/gpfs/projects/gavingrp/dongmeic/beetle/ncfiles/na10km_v2/"
ncin <- nc_open(paste(ncpath,"na10km_v2.nc",sep=""))
x <- ncvar_get(ncin, varid="x"); nx <- length(x)
y <- ncvar_get(ncin, varid="y"); ny <- length(y)
lon <- ncvar_get(ncin, varid="lon")
lat <- ncvar_get(ncin, varid="lat")
nc_close(ncin)

# time
year <- 1997:2016
nt <- length(year)
tunits <- "year"

# define dimensions
xdim <- ncdim_def("x",units="m",longname="x coordinate of projection",as.double(x))
ydim <- ncdim_def("y",units="m",longname="y coordinate of projection",as.double(y))
tdim <- ncdim_def("year",units=tunits,longname="year",as.integer(year))

# define common variables
fillvalue <- 1e32
dlname <- "Longitude of cell center"
lon_def <- ncvar_def("lon","degrees_east",list(xdim,ydim),NULL,dlname,prec="double")
dlname <- "Latitude of cell center"
lat_def <- ncvar_def("lat","degrees_north",list(xdim,ydim),NULL,dlname,prec="double")
projname <- "lambert_azimuthal_equal_area"
proj_def <- ncvar_def(projname,"1",NULL,NULL,longname=dlname,prec="char")
dlname <- "year"
time_def <- ncvar_def(dlname,tunits,list(tdim),NULL,dlname,prec="integer")


# mpb
ncfname <- paste(ncpath,"prs/na10km_v2_mpb_presence.nc", sep="")
<<<<<<< HEAD
csvfile <- "na10km_presence_details_all_2.csv"
=======
csvfile <- "na10km_presence_details_all.csv"
>>>>>>> 9f55ce8226a09b90391de27a36b1dd0e12786bc9
dname <- "mpb_prs"
dlname <- "Mountain pine beetle presence"
dunits <- "binary"

# read and reshape
print("read beetle presence data")
indata <- read.csv(paste(csvpath, csvfile, sep=""))
indata <- indata[,-1]
str(indata)
print("done!")

print("set j and k index")
j2 <- sapply(indata$x, function(xy) which.min(abs(x-xy)))
k2 <- sapply(indata$y, function(xy) which.min(abs(y-xy)))
head(cbind(indata$x,indata$y,j2,k2))
print("done!")

print("create temporary array")
nobs <- dim(indata)[1]
m <- rep(1:nt,each=nobs)
temp_array <- array(fillvalue, dim=c(nx,ny,nt))
temp_array[cbind(j2,k2,m)] <- as.matrix(indata[1:nobs,6:25])
print("done!")

# create netCDF file and put data
print("define the netCDF file")
var_def <- ncvar_def(dname,dunits,list(xdim,ydim,tdim),fillvalue,dlname,prec="float")
ncout <- nc_create(ncfname,list(lon_def,lat_def,var_def,proj_def),force_v4=TRUE, verbose=FALSE)
print("done!")

# put additional attributes into dimension and data variables
print("writing output")
ncatt_put(ncout,"x","axis","X")
ncatt_put(ncout,"x","standard_name","projection_x_coordinate")
ncatt_put(ncout,"x","grid_spacing","10000 m")
ncatt_put(ncout,"x","_CoordinateAxisType","GeoX")
ncatt_put(ncout,"y","axis","Y")
ncatt_put(ncout,"y","standard_name","projection_y_coordinate")
ncatt_put(ncout,"y","grid_spacing","10000 m")
ncatt_put(ncout,"y","_CoordinateAxisType","GeoY")

ncatt_put(ncout,projname,"name",projname)
ncatt_put(ncout,projname,"long_name",projname)
ncatt_put(ncout,projname,"grid_mapping_name",projname)
ncatt_put(ncout,projname,"longitude_of_projection_origin",-100.0)
ncatt_put(ncout,projname,"latitude_of_projection_origin",50.0)
ncatt_put(ncout,projname,"_CoordinateTransformType","Projection")
ncatt_put(ncout,projname,"_CoordinateAxisTypes","GeoX GeoY")
na10km_projstr <- "+proj=laea +lon_0=-100 +lat_0=50 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"
ncatt_put(ncout,projname,"CRS.PROJ.4",na10km_projstr)

# put variables
ncvar_put(ncout,lon_def,lon)
ncvar_put(ncout,lat_def,lat)
ncvar_put(ncout,time_def,year)
ncvar_put(ncout,var_def,temp_array)

# add global attributes
ncatt_put(ncout,0,"title","Yearly beetle presence onto the na10km_v2 10-km Grid")
ncatt_put(ncout,0,"institution","Dept. Geography; Univ_ Oregon")
ncatt_put(ncout,0,"source","generated by interplr.f90")
history <- paste("D.Chen", date(), sep=", ")
ncatt_put(ncout,0,"history",history)
ncatt_put(ncout,0,"base_period","1997-2016")
print("done!")

# add more beetle presence variables
species <- c("jack", "lodgepole", "ponderosa", "pinyon", "sugar", "w_white", "whitebark", "limber")
print("add more beetle presence data")
for (i in 1:length(species)){
  print(i)
  pinenm = paste(species[i], "_mpb_prs", sep="")
  pinelnm = paste("Mountain pine beetle in ", species[i], " pine", sep="")
  pine_def <- ncvar_def(pinenm, dunits, list(xdim, ydim, tdim), fillvalue,pinelnm, prec = "float")
  ncout <- ncvar_add(ncout, pine_def)
  temp_array <- array(fillvalue, dim = c(nx,ny,nt))
  temp_array[cbind(j2,k2,m)] <- as.matrix(indata[1:nobs,(36+nt*(i-1)):(35+nt*i)])  
  ncvar_put(ncout, pine_def, temp_array)
}
print("done!")
dname <- "chosts_mpb_prs"
dlname <- "Mountain pine beetle presence in core hosts"

print("add more beetle presence data")
var_def <- ncvar_def(dname,dunits,list(xdim,ydim,tdim),fillvalue,dlname,prec="float")
ncout <- ncvar_add(ncout, var_def)
temp_array <- array(fillvalue, dim = c(nx,ny,nt))
temp_array[cbind(j2,k2,m)] <- as.matrix(indata[1:nobs,196:215]) 
ncvar_put(ncout, var_def, temp_array)

# close the file, writing data to disk
nc_close(ncout)
print("done!")
